#!/usr/bin/env bash
# scripts/audit-skills.sh
# 复现 2026-06-07 自查:统计所有 plugin/skill/tool 真实调用,对比 ideal-workflow.md
# 输出 docs/superpowers/audits/audit-YYYY-MM-DD.md

set -euo pipefail

PROJ_DIR="${PROJ_DIR:-$HOME/.claude/projects/-Users-gordonwangmbp-Documents-01-project}"
REPO_DIR="${REPO_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
AUDIT_DIR="$REPO_DIR/docs/superpowers/audits"
DATE=$(date +%Y-%m-%d)
OUT="$AUDIT_DIR/audit-$DATE.md"

mkdir -p "$AUDIT_DIR"

if [[ ! -d "$PROJ_DIR" ]]; then
  echo "ERROR: $PROJ_DIR not found" >&2
  exit 1
fi

cd "$PROJ_DIR"

JSONL_COUNT=$(ls *.jsonl 2>/dev/null | wc -l | tr -d ' ')
count() { grep -h "$1" *.jsonl 2>/dev/null | wc -l | tr -d ' '; }

N_SKILL=$(count '"name":"Skill"')
N_AGENT=$(count '"name":"Agent"')
N_TCREATE=$(count '"name":"TaskCreate"')
N_TUPDATE=$(count '"name":"TaskUpdate"')
N_BASH=$(count '"name":"Bash"')
N_READ=$(count '"name":"Read"')
N_WRITE=$(count '"name":"Write"')
N_EDIT=$(count '"name":"Edit"')
N_CG=$(grep -ho 'mcp__codegraph__[a-z_]*' *.jsonl 2>/dev/null | wc -l | tr -d ' ')

if [[ "$JSONL_COUNT" -gt 0 ]]; then
  AVG() { awk -v n="$1" -v s="$JSONL_COUNT" 'BEGIN{printf "%.2f", n/s}'; }
else
  AVG() { echo "0.00"; }
fi

TOP_SKILLS=$(grep -hoE '"skill":"[a-zA-Z:_@/-]+"' *.jsonl 2>/dev/null | sort | uniq -c | sort -rn | head -20 || true)
TOP_AGENTS=$(grep -hoE '"subagent_type":"[a-zA-Z_-]+"' *.jsonl 2>/dev/null | sort | uniq -c | sort -rn | head -10 || true)
TOP_CG=$(grep -hoE 'mcp__codegraph__[a-z_]+' *.jsonl 2>/dev/null | sort | uniq -c | sort -rn | head -10 || true)

cat > "$OUT" <<EOF
# Skill/Tool Audit — $DATE

> Generated by \`scripts/audit-skills.sh\`
> 对比基准:[ideal-workflow.md](../ideal-workflow.md)

## 会话规模

- .jsonl 会话数: **$JSONL_COUNT**

## 工具调用量(累计 + 平均/会话)

| 工具 | 调用 | 平均/会话 | 期望 | 状态 |
|------|------|----------|------|------|
| Skill | $N_SKILL | $(AVG $N_SKILL) | ≥ 2.0 | 待评估 |
| Agent | $N_AGENT | $(AVG $N_AGENT) | ≥ 1.0 | 待评估 |
| TaskCreate | $N_TCREATE | $(AVG $N_TCREATE) | ≥ 0.5 | 待评估 |
| TaskUpdate | $N_TUPDATE | $(AVG $N_TUPDATE) | ≥ 1.0 | 待评估 |
| Bash | $N_BASH | $(AVG $N_BASH) | 40-80 | — |
| Read | $N_READ | $(AVG $N_READ) | 10-25 | — |
| Edit | $N_EDIT | $(AVG $N_EDIT) | 5-15 | — |
| Write | $N_WRITE | $(AVG $N_WRITE) | 1-6 | — |
| mcp__codegraph__* | $N_CG | $(AVG $N_CG) | ≥ 10 | 待评估 |

## Top Skills

\`\`\`
$TOP_SKILLS
\`\`\`

## Top Agents

\`\`\`
$TOP_AGENTS
\`\`\`

## Top CodeGraph 子工具

\`\`\`
$TOP_CG
\`\`\`

---

## 自我对比

(由 Claude 阅读此报告 + ideal-workflow.md 后填)

### 强制 4 skill 当前 vs 目标

| Skill | 当前 | 目标 | 差距 |
|-------|------|------|------|

### 新发现 / 偏差

(列出本次审计相对上次的变化点)

### 下一步行动

(基于差距,提出具体改进)
EOF

echo "Audit written: $OUT"
echo "Summary: $JSONL_COUNT sessions, $N_SKILL skill invocations, $N_CG codegraph calls"
